use clap::{App, Arg, SubCommand};
pub fn build_cli() -> App<'static, 'static> {
    App::new(crate_name!())
        .version(crate_version!())
        .author(crate_authors!())
        .about(crate_description!())
        .args(&[])
        .subcommand(
            SubCommand::with_name("generate")
                .about("generate locations")
                .args(&[
                    //次元の指定
                    Arg::with_name("rank")
                        .short("r")
                        .long("rank")
                        .takes_value(true)
                        .default_value("3"),
                    //個数の取得
                    Arg::with_name("number")
                        .short("n")
                        .long("number")
                        .takes_value(true)
                        .default_value("100"),
                    //出力先
                    Arg::with_name("output")
                        .short("o")
                        .long("output")
                        .value_name("FILE")
                        .takes_value(true),
                    //領域
                    Arg::with_name("scale")
                        .short("s")
                        .long("scale")
                        .takes_value(true)
                        .default_value("1.0"),
                    //シード値
                    Arg::with_name("seed")
                        .short("t")
                        .long("seed")
                        .takes_value(true),
                ]),
        )
        .subcommand(
            SubCommand::with_name("demo").args(&[
                //入力元
                Arg::with_name("location")
                    .short("l")
                    .long("location")
                    .value_name("FILE")
                    .takes_value(true),
                //出力先
                Arg::with_name("output")
                    .short("o")
                    .long("output")
                    .value_name("FILE")
                    .takes_value(true),
                //モード
                Arg::with_name("mode")
                    .short("m")
                    .long("mode")
                    .takes_value(true)
                    .possible_values(&["order"])
                    .default_value("order"),
            ]),
        )
        .subcommand(
            SubCommand::with_name("check").args(&[
                //順番
                Arg::with_name("path file")
                    .short("p")
                    .long("path")
                    .value_name("FILE")
                    .help("index path")
                    .takes_value(true),
                //場所
                Arg::with_name("location")
                    .short("l")
                    .long("location")
                    .value_name("FILE")
                    .required(true)
                    .takes_value(true),
            ]),
        )
}
